# Dockerfile_proxy

FROM python:3.8

WORKDIR /app

# Install dependencies
COPY requirements_proxy.txt .
RUN pip install --no-cache-dir -r requirements_proxy.txt

# Copy application code
COPY proxy.py .

# Expose port
EXPOSE 6000

# Run the application
CMD ["python", "proxy.py"]
