# Dockerfile_B_async

FROM python:3.8

WORKDIR /app

# Install dependencies
COPY imagenet_classes.txt .
COPY resnet50-pretrained.pth .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy model structure code
COPY model_definitions1.py .
COPY model_definitions2.py .
COPY model_definitions3.py .

# Create models directory and copy model files
RUN mkdir models
COPY models/ models/

# Copy application code
COPY server_b_async.py .

# Expose port
EXPOSE 5001

# Set default environment variable
ENV MODEL_VERSION=1

# Run the application
CMD ["python3", "server_b_async.py"]
